name: test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
          channels: conda-forge

      - name: Install deps
        run: |
          conda install mamba pip
          which pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: install lib
        run: |
          which pip
          pip install -e . --no-deps --force-reinstall

      - name: run-test
        run:
          cp -r tests/ "${RUNNER_TEMP}/"
          pushd "${RUNNER_TEMP}"
          pytest -vrsx -n 2 -rxs --cov=conda_lock tests

      - name: test-gdal
        run: |
          pushd "${RUNNER_TEMP}/tests/gdal"
          conda-lock -f environment.yml -p linux-64


